---
title: for
categories: [ "Structure" ]
subCategories: [ "Control Structure" ]
---





= for loop


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Descripción
La sentencia `for` se usa para repetir un bloque de sentencias encerradas entre llaves. Un contador incremental se usa generalmente para incrementar y terminar el ciclo. La sentencia `for` es es útil para cualquier operación repetitiva, y a menudo se usa en combinación con matrices para operar en colecciones de datos / pines.
[%hardbreaks]


[float]
=== Sintaxis
[source,arduino]
----
for (inicialización; condición; incremento) {
	//sentencia(s);
}
----

===Parámetros
La *initialization* sucede primero y sólo una vez. En cada ejecución del bucle, la *condición* se prueba, si es `true`, el bloque de sentencias y el *incremento* se ejecutan, luego la condición se prueba nuevamente. Cuando la *condición* se vuelve 'false', el ciclo termina.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Código de ejemplo
[source,arduino]
----
// Dim an LED using a PWM pin
int PWMpin = 10; // Un LED en serie con una resistencia de 470 ohm en el pin 10.

void setup()
{
  // no se necesita setup
}

void loop()
{
   for (int i=0; i <= 255; i++){
      analogWrite(PWMpin, i);
      delay(10);
   }
}
----
[%hardbreaks]

[float]
=== Notas y advertencias
En C `for` loop es mucho más flexible que los bucles `for` que se encuentran en otros lenguajes de computadora, incluido BASIC. Cualquiera o todos los tres elementos de encabezado pueden omitirse, aunque se requieren los puntos y comas. Además, las declaraciones para la inicialización, la condición y el incremento pueden ser declaraciones válidas de C con variables no relacionadas y utilizar cualquier tipo de datos de C,  incluidos los flotantes. statements with unrelated variables, and use any C datatypes including floats. Este tipo de intrucciones `for` inusuales pueden proporcionar soluciones a algunos problemas de programación poco comunes.
[%hardbreaks]

Por ejemplo, usar una multiplicación en la línea de incremento generará una progresión logarítmica:

[source,arduino]
----
for(int x = 2; x < 100; x = x * 1.5){
println(x);
}
----

Genera: 2,3,4,6,9,13,19,28,42,63,94
[%hardbreaks]

Otro ejemplo, desvanenecer y encender un LED con un ciclo `for`:

[source,arduino]
----
void loop()
{
   int x = 1;
   for (int i = 0; i > -1; i = i + x){
      analogWrite(PWMpin, i);
      if (i == 255) x = -1;             // Cambia la dirección en los extremos
      delay(10);
   }
}
----


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== See also

[role="language"]

--
// SEE ALSO SECTION ENDS
